In [1]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('user_clusters.db')

# Query all data from the recommendations table
df_db_view = pd.read_sql_query("SELECT * FROM user_clusters", conn)
conn.close()

# Display the results
print(f"Database contains {len(df_db_view)} records.")
display(df_db_view.head(20))

Database contains 1071 records.

,user_id,cluster_id,active_service,cross_recommend_1,cross_recommend_2,rec1_score,rec2_score,rec1_source,rec2_source,user_display_name,active_service_name,rec1_name,rec2_name,segment_name
0,0053d8ff-8df9-4a10-8992-6e49ca332d14,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
1,0081b91d-92a3-4f34-bfb9-5ab36bfcd1b0,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
2,0085dafd-e825-4afb-a8f8-4828c590242f,0,APPLICATION_DRAFTING,SYNOPSIS_GENERATION,RESEARCH,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Synopsis Generation,Legal Research,Heavy Draftsman
3,00c9515c-f0fb-47c0-85c8-3d694a392106,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
4,0114f882-e950-422d-a53f-79ee8e673a66,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
5,01521c0e-6263-4cd1-94b4-d817904b0ff8,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
6,016c9315-9603-4c7b-8ca1-c732647e9e12,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
7,01c894a6-0e26-4441-9ec0-72760c106c2c,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
8,01d81710-c0cc-432f-8752-fc6149941ec8,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
9,01fcec53-14ca-4830-8b2a-a98cc0640fb4,0,APPLICATION_DRAFTING,SYNOPSIS_GENERATION,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Synopsis Generation,Document Embedding,Heavy Draftsman
10,02b2f0af-638b-4c48-a1aa-4404d930eb12,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
11,02fa5566-512a-4de8-9e6e-25d2bb093492,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
12,03059652-1670-4a88-9250-cbe536efcdda,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (long, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
13,03516abc-75b2-4271-81d6-a5691b410477,0,APPLICATION_DRAFTING,SYNOPSIS_GENERATION,RESEARCH,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Synopsis Generation,Legal Research,Heavy Draftsman
14,03c4ac4d-6ed6-4831-a895-3b441d65b827,0,APPLICATION_DRAFTING,SYNOPSIS_GENERATION,RESEARCH,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Synopsis Generation,Legal Research,Heavy Draftsman
15,03ce26eb-de06-4efb-be66-3168f49e0104,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
16,03d0f2cd-83db-45d2-b119-886c56de5986,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
17,04464490-84a9-4884-8feb-f21a365ebae5,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
18,04521cac-ff48-47a7-85b7-449c65f7e303,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman
19,051a15e5-c6d2-4b0f-bcaa-ade69b70662c,0,APPLICATION_DRAFTING,QUERY_ANSWER,DOCUMENT_EMBEDDING,100.0,60.0,als,als,"Drafting: General Document (short, english)",Application Drafting,Query Answer,Document Embedding,Heavy Draftsman

In [2]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('user_clusters_new.db')

# Query all data from the recommendations table
df_db_view = pd.read_sql_query("SELECT * FROM user_clusters", conn)
conn.close()

# Display the results
print(f"Database contains {len(df_db_view)} records.")
display(df_db_view.head(20))

Database contains 1077 records.

,user_id,Name,cluster_id,active_service,cross_recommend_1,cross_recommend_2
0,36599172-20ed-4b49-9e76-edbee9f65371,Hitesh Khubchandani,0,Inactive,Draft,Research
1,504dd308-847d-474f-84d7-ab86d757d0dd,Guru,2,Draft,Research,Draft
2,132308cd-f1be-4280-8de2-594fed9afc29,Amit Yadav,0,Query,Review,Draft
3,63a18d1e-a730-42c6-8db6-16e932b93088,Aditya Sharma,0,Draft,Research,Draft
4,595c5433-728e-448a-81da-07fec7ccf3f9,Aruna Balkrishna,0,Inactive,Draft,Research
5,4e1d23d7-cbd1-49c1-bcdf-b900eca98800,Shambhavi Singh,2,Draft,Research,Review
6,5858cad9-069a-4e0a-a54d-e6a7ad7b3d02,06- HARSH BHARAD -,0,Inactive,Draft,Research
7,388a1b0a-287c-489b-98bf-b3d02790c0f1,Krish Biraj,2,Draft,Research,Draft
8,57602118-1507-4dbc-9ff2-aac25c272ae8,Naman Rajput,0,Inactive,Draft,Research
9,5afa04e5-85fc-4bd2-b529-5971f5680341,Suhail Malik,2,Draft,Research,Draft
10,5697b1d3-5446-4d0b-90ec-9ff8b984c6b2,Anjali Sharma,0,Inactive,Draft,Research
11,d764a209-613f-445b-a502-22df893e5ab1,H M Sunil,0,Inactive,Draft,Research
12,9c19b04e-dce4-47c0-92e1-be505a099821,Hrishikesh Honkalas,0,Draft,Research,Draft
13,7b13efe3-5f85-4db1-b5cf-e74af46e16c2,Guruprasad Ganjiyavar,0,Draft,Research,Draft
14,bec4a22a-4407-4bcd-b207-0d4f575edac4,Priya Shah,0,Query,Draft,Research
15,7a81a94c-03e2-4483-be6d-fd936e90c2b9,Golvadiya Golvadiya,0,Inactive,Draft,Research
16,999ed535-21c4-4fa5-8b81-127566d1b6a1,Mahesh Golivadiya,0,Inactive,Draft,Research
17,daf4a0ab-c1c4-4cfb-929c-a8ad876ecf04,Rinkoo Patel,0,Inactive,Draft,Research
18,4c92d265-5e0b-4afb-b89d-9db2e2ab4ca0,Disha Shah,0,Draft,Research,Draft
19,d0a9ea08-f798-4d9e-9e41-c46be3fe1e09,Anjali Sharma,2,Draft,Research,Draft

In [4]:
import sqlite3

old = sqlite3.connect('user_clusters.db')
new = sqlite3.connect('user_clusters_new.db')

# Step 1: Add Name column to old DB
old.execute("ALTER TABLE user_clusters ADD COLUMN Name TEXT")

# Step 2: Copy names from new DB
new_names = new.execute("SELECT user_id, Name FROM user_clusters").fetchall()

# Step 3: Update old DB
old.executemany("UPDATE user_clusters SET Name=? WHERE user_id=?", 
                [(name, uid) for uid, name in new_names])

old.commit()
old.close()
new.close()
print("Done!")

Done!

In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('user_clusters.db')

df = pd.read_sql("SELECT user_id, Name, cluster_id FROM user_clusters LIMIT 10", conn)
print(df)

conn.close()

                                user_id                Name  cluster_id
0  0053d8ff-8df9-4a10-8992-6e49ca332d14          Sarathsiva           0
1  0081b91d-92a3-4f34-bfb9-5ab36bfcd1b0   Dmanly marshilong           0
2  0085dafd-e825-4afb-a8f8-4828c590242f       PRAKHAR SINGH           0
3  00c9515c-f0fb-47c0-85c8-3d694a392106  NITESHWAR BHARDWAJ           0
4  0114f882-e950-422d-a53f-79ee8e673a66         vijay kumar           0
5  01521c0e-6263-4cd1-94b4-d817904b0ff8           abu sabah           0
6  016c9315-9603-4c7b-8ca1-c732647e9e12       Soumili Patra           0
7  01c894a6-0e26-4441-9ec0-72760c106c2c         Vikas Verma           0
8  01d81710-c0cc-432f-8752-fc6149941ec8        Akshay varme           0
9  01fcec53-14ca-4830-8b2a-a98cc0640fb4         kunal joshi           0

In [6]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('user_clusters_new.db')

df = pd.read_sql("SELECT user_id, Name, cluster_id FROM user_clusters LIMIT 10", conn)
print(df)

conn.close()

                                user_id                 Name  cluster_id
0  36599172-20ed-4b49-9e76-edbee9f65371  Hitesh Khubchandani           0
1  504dd308-847d-474f-84d7-ab86d757d0dd                 Guru           2
2  132308cd-f1be-4280-8de2-594fed9afc29           Amit Yadav           0
3  63a18d1e-a730-42c6-8db6-16e932b93088        Aditya Sharma           0
4  595c5433-728e-448a-81da-07fec7ccf3f9     Aruna Balkrishna           0
5  4e1d23d7-cbd1-49c1-bcdf-b900eca98800      Shambhavi Singh           2
6  5858cad9-069a-4e0a-a54d-e6a7ad7b3d02   06- HARSH BHARAD -           0
7  388a1b0a-287c-489b-98bf-b3d02790c0f1          Krish Biraj           2
8  57602118-1507-4dbc-9ff2-aac25c272ae8         Naman Rajput           0
9  5afa04e5-85fc-4bd2-b529-5971f5680341         Suhail Malik           2

In [7]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('user_clusters_new.db')

# Query all data from the recommendations table
df_db_view = pd.read_sql_query("SELECT * FROM user_clusters", conn)
conn.close()

# Display the results
print(f"Database contains {len(df_db_view)} records.")
display(df_db_view.head(20))

Database contains 1077 records.

,user_id,Name,cluster_id,active_service,cross_recommend_1,cross_recommend_2
0,36599172-20ed-4b49-9e76-edbee9f65371,Hitesh Khubchandani,0,Inactive,Draft,Research
1,504dd308-847d-474f-84d7-ab86d757d0dd,Guru,2,Draft,Research,Draft
2,132308cd-f1be-4280-8de2-594fed9afc29,Amit Yadav,0,Query,Review,Draft
3,63a18d1e-a730-42c6-8db6-16e932b93088,Aditya Sharma,0,Draft,Research,Draft
4,595c5433-728e-448a-81da-07fec7ccf3f9,Aruna Balkrishna,0,Inactive,Draft,Research
5,4e1d23d7-cbd1-49c1-bcdf-b900eca98800,Shambhavi Singh,2,Draft,Research,Review
6,5858cad9-069a-4e0a-a54d-e6a7ad7b3d02,06- HARSH BHARAD -,0,Inactive,Draft,Research
7,388a1b0a-287c-489b-98bf-b3d02790c0f1,Krish Biraj,2,Draft,Research,Draft
8,57602118-1507-4dbc-9ff2-aac25c272ae8,Naman Rajput,0,Inactive,Draft,Research
9,5afa04e5-85fc-4bd2-b529-5971f5680341,Suhail Malik,2,Draft,Research,Draft
10,5697b1d3-5446-4d0b-90ec-9ff8b984c6b2,Anjali Sharma,0,Inactive,Draft,Research
11,d764a209-613f-445b-a502-22df893e5ab1,H M Sunil,0,Inactive,Draft,Research
12,9c19b04e-dce4-47c0-92e1-be505a099821,Hrishikesh Honkalas,0,Draft,Research,Draft
13,7b13efe3-5f85-4db1-b5cf-e74af46e16c2,Guruprasad Ganjiyavar,0,Draft,Research,Draft
14,bec4a22a-4407-4bcd-b207-0d4f575edac4,Priya Shah,0,Query,Draft,Research
15,7a81a94c-03e2-4483-be6d-fd936e90c2b9,Golvadiya Golvadiya,0,Inactive,Draft,Research
16,999ed535-21c4-4fa5-8b81-127566d1b6a1,Mahesh Golivadiya,0,Inactive,Draft,Research
17,daf4a0ab-c1c4-4cfb-929c-a8ad876ecf04,Rinkoo Patel,0,Inactive,Draft,Research
18,4c92d265-5e0b-4afb-b89d-9db2e2ab4ca0,Disha Shah,0,Draft,Research,Draft
19,d0a9ea08-f798-4d9e-9e41-c46be3fe1e09,Anjali Sharma,2,Draft,Research,Draft

In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('user_clusters_new.db')

df = pd.read_sql("SELECT user_id, Name FROM user_clusters LIMIT 10", conn)
print(df)

conn.close()

                                user_id                 Name
0  36599172-20ed-4b49-9e76-edbee9f65371  Hitesh Khubchandani
1  504dd308-847d-474f-84d7-ab86d757d0dd                 Guru
2  132308cd-f1be-4280-8de2-594fed9afc29           Amit Yadav
3  63a18d1e-a730-42c6-8db6-16e932b93088        Aditya Sharma
4  595c5433-728e-448a-81da-07fec7ccf3f9     Aruna Balkrishna
5  4e1d23d7-cbd1-49c1-bcdf-b900eca98800      Shambhavi Singh
6  5858cad9-069a-4e0a-a54d-e6a7ad7b3d02   06- HARSH BHARAD -
7  388a1b0a-287c-489b-98bf-b3d02790c0f1          Krish Biraj
8  57602118-1507-4dbc-9ff2-aac25c272ae8         Naman Rajput
9  5afa04e5-85fc-4bd2-b529-5971f5680341         Suhail Malik